### ISSUE TITLE
External link tracking in google not displaying link. Just says "External link"

### ISSUE THREAD

**Issue by developering** [stepframe/jquery-steplinks#1] opened 2015-11-16 22:50 UTC

**Comment by nancyobrien** [comment] 2015-11-17 00:01
This is a basic misunderstanding of how Google Analytics Event tracking works.  "External Link" is the event category.  If you view events by event label or event action you can see the link url or the title of the link.  Not a bug.  Closing. :)

**Closed as completed by nancyobrien** 2015-11-17 00:01 UTC
